//
//  UIColor+GVAdditions.swift
//
//  Generated by Zeplin on 6/6/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
  
  public final func alpha(_ alpha: CGFloat) -> UIColor {
    return withAlphaComponent(alpha)
  }
}
