//
//  DayWeatherDataViewController.swift
//  WeatherApp
//
//  Created by Alvyn SILOU on 06/10/2018.
//  Copyright (c) 2018 Alvyn SILOU. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DayWeatherDataDisplayLogic: class
{
  func displayDaysWeatherData(viewModel: DayWeatherData.FetchDaysWeatherData.ViewModel)
}

class DayWeatherDataViewController: UIViewController, DayWeatherDataDisplayLogic
{
  var interactor: DayWeatherDataBusinessLogic?
  var router: (NSObjectProtocol & DayWeatherDataRoutingLogic & DayWeatherDataDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = DayWeatherDataInteractor()
    let presenter = DayWeatherDataPresenter()
    let router = DayWeatherDataRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    fetchDaysWeatherData()
  }
  
  // MARK: FetchDaysWeatherData
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func fetchDaysWeatherData()
  {
    let request = DayWeatherData.FetchDaysWeatherData.Request()
    interactor?.fetchDaysWeatherData(request: request)
  }
  
  func displayDaysWeatherData(viewModel: DayWeatherData.FetchDaysWeatherData.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
  
  func canBeRoutingTo() -> Bool {
    return self.router?.dataStore?.interimStatements == nil
  }
  var detailItem: NSDate? {
    didSet {
      // Update the view.
    }
  }
}
