//
//  DayWeatherDataRouter.swift
//  WeatherApp
//
//  Created by Alvyn SILOU on 06/10/2018.
//  Copyright (c) 2018 Alvyn SILOU. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DayWeatherDataRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol DayWeatherDataDataPassing
{
  var dataStore: DayWeatherDataDataStore? { get }
}

class DayWeatherDataRouter: NSObject, DayWeatherDataRoutingLogic, DayWeatherDataDataPassing
{
  weak var viewController: DayWeatherDataViewController?
  var dataStore: DayWeatherDataDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: DayWeatherDataViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: DayWeatherDataDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
