//
//  DayWeatherDataModels.swift
//  WeatherApp
//
//  Created by Alvyn SILOU on 06/10/2018.
//  Copyright (c) 2018 Alvyn SILOU. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DayWeatherData
{
  // MARK: Use cases
  
  enum FetchDaysWeatherData
  {
    struct Request
    {
    }
    struct Response
    {
      let daysWeatherData:  [DailyInterimStatement]
    }
    struct ViewModel
    {
      struct DisplayedInterimStatement {
        var time: NSAttributedString
        var temperature: NSAttributedString
        var rain: NSAttributedString
        var moisture: NSAttributedString
        var averageWind: NSAttributedString
        var pressure: NSAttributedString
      }
      
      let displayedInterimStatements: [DisplayedInterimStatement]
    }
  }
}
