//
//  DayWeatherDataModels.swift
//  WeatherApp
//
//  Created by Alvyn SILOU on 06/10/2018.
//  Copyright (c) 2018 Alvyn SILOU. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DayWeatherData
{
  // MARK: Use cases
  
  enum FetchDaysWeatherData
  {
    struct Request
    {
    }
    struct Response
    {
      let daysWeatherData:  [DailyInterimStatement]
    }
    
    struct ViewModel
    {
      struct DisplayedInterimStatement {
        var time: String = "Heure"
        var temperature: String = "Température"
        var rain: String = "Pluie"
        var moisture: String = "Humidité"
        var averageWind: String = "Vent"
        var pressure: String = "Pression"
      }
      
      let displayedInterimStatements: [DisplayedInterimStatement]
    }
    
  }
}

typealias DisplayedInterimStatement = DayWeatherData.FetchDaysWeatherData.ViewModel.DisplayedInterimStatement
 extension DisplayedInterimStatement {
  
  init(interimStatement: DailyInterimStatement) {
    self.temperature = "\(interimStatement.temperatureInDegreeCelsius)°c"
    self.time = "\(interimStatement.time.hour)h"
    self.averageWind = "\(interimStatement.averageWind) km/h"
    self.moisture = "\(interimStatement.moisture)%"
    self.rain = "\(interimStatement.rain) mm/1h"
    self.pressure = "\(interimStatement.pressure) hPa"
  }
}

