//
//  WeatherForecastsRouter.swift
//  WeatherApp
//
//  Created by Alvyn SILOU on 06/10/2018.
//  Copyright (c) 2018 Alvyn SILOU. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WeatherForecastsRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol WeatherForecastsDataPassing
{
  var dataStore: WeatherForecastsDataStore? { get }
}

class WeatherForecastsRouter: NSObject, WeatherForecastsRoutingLogic, WeatherForecastsDataPassing
{
  weak var viewController: WeatherForecastsViewController?
  var dataStore: WeatherForecastsDataStore?
  weak var detailViewController: DayWeatherDataViewController? = nil

  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: WeatherForecastsViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: WeatherForecastsDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
