//
//  WeatherForecastsPresenter.swift
//  WeatherApp
//
//  Created by Alvyn SILOU on 06/10/2018.
//  Copyright (c) 2018 Alvyn SILOU. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherForecastsPresentationLogic
{
  func presentWeatherForecasts(response: WeatherForecasts.FetchWeatherData.Response)
}

class WeatherForecastsPresenter: WeatherForecastsPresentationLogic
{
  weak var viewController: WeatherForecastsDisplayLogic?
  
  // MARK: FetchWeatherData
  
  func presentWeatherForecasts(response: WeatherForecasts.FetchWeatherData.Response)
  {
    let transformedViewModels = transformToDisplayedWeatherData(statements: response.interimStatements)
    let viewModel = WeatherForecasts.FetchWeatherData.ViewModel(weatherData:transformedViewModels)
    viewController?.displayWeatherForecasts(viewModel: viewModel)
  }
}

extension WeatherForecastsPresenter {
  private func transformToDisplayedWeatherData(statements: [Date: [DailyInterimStatement]]) -> [WeatherForecasts.FetchWeatherData.ViewModel.DaysWeatherData] {
    
    return statements.map({
      let minMax = $0.value.minMaxTemperature()
      return WeatherForecasts.FetchWeatherData.ViewModel.DaysWeatherData(date: $0.key, minTemperature: minMax?.min ?? 0, maxTemperature: minMax?.max ?? 0)
    }).sorted(by: { v1, v2 in v1.date < v2.date })
  }
}

