//
//  WeatherForecastsRouter.swift
//  WeatherApp
//
//  Created by Alvyn SILOU on 06/10/2018.
//  Copyright (c) 2018 Alvyn SILOU. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WeatherForecastsRoutingLogic
{
  func routeToDetail(segue: UIStoryboardSegue?)
}

protocol WeatherForecastsDataPassing
{
  var dataStore: WeatherForecastsDataStore? { get }
}

class WeatherForecastsRouter: NSObject, WeatherForecastsRoutingLogic, WeatherForecastsDataPassing
{
  weak var viewController: WeatherForecastsViewController?
  var dataStore: WeatherForecastsDataStore?
  weak var detailViewController: DayWeatherDataViewController? = nil

  // MARK: Routing
  
  func routeToDetail(segue: UIStoryboardSegue?)
  {
    beginByHandlingSelectionEvent()
    if let segue = segue {
      let destinationVC = (segue.destination as! UINavigationController).topViewController as! DayWeatherDataViewController
      
      var destinationDS = destinationVC.router!.dataStore!
      passDataToDetail(source: dataStore!, destination: &destinationDS)
    } else {
      // Using Storyboard
    }
  }

  private func     beginByHandlingSelectionEvent() {
    if let indexPath = viewController?.tableView.indexPathForSelectedRow,
      let dateSelected = viewController?.weatherData[indexPath.row].date {
      viewController?.dateSelected = dateSelected
      viewController?.showDaysWeatherData()
    }
  }
  
  // MARK: Navigation
  
  //func navigateToSomewhere(source: WeatherForecastsViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  func passDataToDetail(source: WeatherForecastsDataStore, destination: inout DayWeatherDataDataStore)
  {
    let arrayOfData = source.interimStatementsOfSelectedDay
    destination.interimStatements = arrayOfData.isEmpty ? nil : arrayOfData
  }
}
