//
//  WeatherForecastsInteractor.swift
//  WeatherApp
//
//  Created by Alvyn SILOU on 06/10/2018.
//  Copyright (c) 2018 Alvyn SILOU. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherForecastsBusinessLogic
{
  func fetchWeatherForecasts(request: WeatherForecasts.FetchWeatherData.Request)
}

protocol WeatherForecastsDataStore
{

}

class WeatherForecastsInteractor: WeatherForecastsBusinessLogic, WeatherForecastsDataStore
{
  var presenter: WeatherForecastsPresentationLogic?
  var worker: WeatherForecastsWorker?
  
  // MARK: FetchWeatherData
  
  func fetchWeatherForecasts(request: WeatherForecasts.FetchWeatherData.Request)
  {
    worker = WeatherForecastsWorker()
    worker?.doSomeWork()
    
    let response = WeatherForecasts.FetchWeatherData.Response()
    presenter?.presentWeatherForecasts(response: response)
  }
}
